"""Bug fixing

Revision ID: 0137b92d0ac2
Revises: f100b2ec8c3f
Create Date: 2017-11-02 10:12:43.537943

"""

# revision identifiers, used by Alembic.
revision = '0137b92d0ac2'
down_revision = 'f100b2ec8c3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
