"""Adding days worked from home q

Revision ID: 0e5d053a6897
Revises: 3f4088946d27
Create Date: 2017-10-16 15:05:15.371005

"""

# revision identifiers, used by Alembic.
revision = '0e5d053a6897'
down_revision = '3f4088946d27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('primary_programming_language_used_at_work', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'how_many_days_per_week_you_work_from_home')
    # ### end Alembic commands ###
