"""Changing annual_amount_earned... to total_compensation

Revision ID: 198aac62931f
Revises: 0137b92d0ac2
Create Date: 2017-11-12 10:55:49.419098

"""

# revision identifiers, used by Alembic.
revision = '198aac62931f'
down_revision = '0137b92d0ac2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('annual_amount_earned_from_all_tech_activities_combined', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('users', 'total_compensation')
    # ### end Alembic commands ###
