"""Adding fav sports team q

Revision ID: 1b42576891e0
Revises: 7f09da8a0364
Create Date: 2017-10-16 17:59:32.299248

"""

# revision identifiers, used by Alembic.
revision = '1b42576891e0'
down_revision = '7f09da8a0364'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('primary_programming_language_used_at_work', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'favorite_cleveland_pro_sports_team')
    # ### end Alembic commands ###
