"""Adding version control q

Revision ID: 2d790d67eeca
Revises: 97a0a45ae75b
Create Date: 2017-10-16 14:53:17.858790

"""

# revision identifiers, used by Alembic.
revision = '2d790d67eeca'
down_revision = '97a0a45ae75b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('primary_programming_language_used_at_work', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'primary_version_control_systems_used_at_work')
    # ### end Alembic commands ###
