"""Adding annual cash earned q

Revision ID: 3888fccede21
Revises: 2d790d67eeca
Create Date: 2017-10-16 14:58:42.497515

"""

# revision identifiers, used by Alembic.
revision = '3888fccede21'
down_revision = '2d790d67eeca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('primary_programming_language_used_at_work', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'annual_amount_earned_from_all_tech_activities_combined')
    # ### end Alembic commands ###
