"""Removing bad column names

Revision ID: 4857812d7ce4
Revises: 6300ad79d042
Create Date: 2017-10-15 15:24:37.658069

"""

# revision identifiers, used by Alembic.
revision = '4857812d7ce4'
down_revision = '6300ad79d042'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'years_of_pro_exp')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('years_of_professional_experience', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
