"""Adding more to User table

Revision ID: 52f8698173d0
Revises: d4e4c95f0d18
Create Date: 2017-10-15 18:55:07.110953

"""

# revision identifiers, used by Alembic.
revision = '52f8698173d0'
down_revision = 'd4e4c95f0d18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'highest_educational_attainment')
    # ### end Alembic commands ###
