"""Adding gender and ethnicity to User

Revision ID: 5ae9c75d0cc6
Revises: a8a45d68771c
Create Date: 2017-10-14 13:46:51.416624

"""

# revision identifiers, used by Alembic.
revision = '5ae9c75d0cc6'
down_revision = 'a8a45d68771c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ethnicity', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'ethnicity')
    # ### end Alembic commands ###
