"""Adding more qs

Revision ID: 64568605d624
Revises: 96f7cf9e2d24
Create Date: 2017-10-16 15:21:54.611532

"""

# revision identifiers, used by Alembic.
revision = '64568605d624'
down_revision = '96f7cf9e2d24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('primary_programming_language_used_at_work', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'work_life_balance')
    op.drop_column('users', 'most_annoying_work_issue')
    op.drop_column('users', 'how_you_found_your_current_job')
    # ### end Alembic commands ###
