"""Adding more to User table

Revision ID: 75cdc270bc35
Revises: e26e7864df4b
Create Date: 2017-10-16 08:47:04.999233

"""

# revision identifiers, used by Alembic.
revision = '75cdc270bc35'
down_revision = 'e26e7864df4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'primary_programming_language_used_at_work')
    op.drop_column('users', 'how_you_learned_to_code')
    # ### end Alembic commands ###
