"""Removing excess db columns

Revision ID: 7b5cfc5492b1
Revises: d3a7a128b9fb
Create Date: 2017-12-15 15:30:40.499573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5cfc5492b1'
down_revision = 'd3a7a128b9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_column('users', 'jobs')
    # op.drop_column('users', 'name')
    # op.drop_column('users', 'member_since')
    # op.drop_column('users', 'about_me')
    # op.drop_column('users', 'location')
    # op.drop_column('users', 'annual_amount_earned_from_all_tech_activities_combined')
    # op.drop_column('users', 'avatar_hash')
    # op.drop_column('users', 'years_of_pro_exp')
    # op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('avatar_hash', sa.VARCHAR(length=32), nullable=True))
    op.add_column('users', sa.Column('annual_amount_earned_from_all_tech_activities_combined', sa.VARCHAR(length=32), nullable=True))
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
