"""Adding keeps you in cle q

Revision ID: 7f09da8a0364
Revises: 7e1236a3c51f
Create Date: 2017-10-16 17:57:03.895941

"""

# revision identifiers, used by Alembic.
revision = '7f09da8a0364'
down_revision = '7e1236a3c51f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('primary_programming_language_used_at_work', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'what_keeps_you_in_cleveland')
    # ### end Alembic commands ###
