"""Changing tech_role to tech_roles

Revision ID: 88893dd5150d
Revises: cdea2621fafb
Create Date: 2017-10-15 15:40:18.439584

"""

# revision identifiers, used by Alembic.
revision = '88893dd5150d'
down_revision = 'cdea2621fafb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'tech_roles')
    # ### end Alembic commands ###
