"""Adding survey functionality

Revision ID: 8acf26b29670
Revises: a8ace8440b14
Create Date: 2017-10-13 08:39:20.319368

"""

# revision identifiers, used by Alembic.
revision = '8acf26b29670'
down_revision = 'a8ace8440b14'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jobs', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jobs')
    # ### end Alembic commands ###
