"""initial post-deploy migration

Revision ID: 9765a92e9d57
Revises: 
Create Date: 2017-11-29 20:02:38.609134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9765a92e9d57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('annual_amount_earned_from_all_tech_activities_combined', sa.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
