"""Adding dev env q

Revision ID: 97a0a45ae75b
Revises: 6e5c2fa5f071
Create Date: 2017-10-16 14:23:22.441787

"""

# revision identifiers, used by Alembic.
revision = '97a0a45ae75b'
down_revision = '6e5c2fa5f071'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('primary_programming_language_used_at_work', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'primary_development_environments_used_at_work')
    # ### end Alembic commands ###
