"""Adding years of pro exp column

Revision ID: a8a45d68771c
Revises: 8acf26b29670
Create Date: 2017-10-13 10:40:08.416417

"""

# revision identifiers, used by Alembic.
revision = 'a8a45d68771c'
down_revision = '8acf26b29670'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('years_of_pro_exp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'years_of_pro_exp')
    # ### end Alembic commands ###
