"""Testing

Revision ID: b69e2751753b
Revises: 
Create Date: 2017-11-29 20:46:18.103990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69e2751753b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_table('roles',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=64), nullable=True),
    # sa.Column('default', sa.Boolean(), nullable=True),
    # sa.Column('permissions', sa.Integer(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    # )
    # op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(length=64), nullable=True),
    # sa.Column('username', sa.String(length=64), nullable=True),
    # sa.Column('role_id', sa.Integer(), nullable=True),
    # sa.Column('password_hash', sa.String(length=128), nullable=True),
    # sa.Column('confirmed', sa.Boolean(), nullable=True),
    # sa.Column('name', sa.String(length=64), nullable=True),
    # sa.Column('location', sa.String(length=64), nullable=True),
    # sa.Column('about_me', sa.Text(), nullable=True),
    # sa.Column('member_since', sa.DateTime(), nullable=True),
    # sa.Column('last_seen', sa.DateTime(), nullable=True),
    # sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    # sa.Column('gender', sa.String(length=64), nullable=True),
    # sa.Column('ethnicity', sa.String(length=64), nullable=True),
    # sa.Column('highest_educational_attainment', sa.String(length=64), nullable=True),
    # sa.Column('undergraduate_major', sa.String(length=64), nullable=True),
    # sa.Column('how_you_learned_to_code', sa.String(length=128), nullable=True),
    # sa.Column('primary_programming_languages_used_at_work', sa.String(length=128), nullable=True),
    # sa.Column('primary_database_technologies_used_at_work', sa.String(length=128), nullable=True),
    # sa.Column('primary_platforms_used_at_work', sa.String(length=128), nullable=True),
    # sa.Column('primary_development_environments_used_at_work', sa.String(length=128), nullable=True),
    # sa.Column('primary_version_control_systems_used_at_work', sa.String(length=128), nullable=True),
    # sa.Column('tech_roles', sa.String(length=128), nullable=True),
    # sa.Column('years_of_professional_experience', sa.Integer(), nullable=True),
    # sa.Column('total_compensation', sa.String(length=32), nullable=True),
    # sa.Column('satisfaction_with_compensation', sa.Integer(), nullable=True),
    # sa.Column('what_you_value_most_in_compensation', sa.String(length=128), nullable=True),
    # sa.Column('how_many_days_per_week_you_work_from_home', sa.Integer(), nullable=True),
    # sa.Column('company_size', sa.String(length=32), nullable=True),
    # sa.Column('total_hours_worked_per_week', sa.Integer(), nullable=True),
    # sa.Column('job_satisfaction', sa.Integer(), nullable=True),
    # sa.Column('a_customer_calls_late_friday_evening', sa.String(length=64), nullable=True),
    # sa.Column('work_life_balance', sa.Integer(), nullable=True),
    # sa.Column('how_you_found_your_current_job', sa.String(length=128), nullable=True),
    # sa.Column('most_annoying_work_issue', sa.String(length=128), nullable=True),
    # sa.Column('favorite_office_perk', sa.String(length=128), nullable=True),
    # sa.Column('what_keeps_you_in_cleveland', sa.String(length=128), nullable=True),
    # sa.Column('favorite_cleveland_pro_sports_team', sa.String(length=64), nullable=True),
    # sa.Column('favorite_cleveland_hangout_area', sa.String(length=32), nullable=True),
    # sa.Column('favorite_cleveland_activity', sa.String(length=32), nullable=True),
    # sa.Column('feedback', sa.String(length=64), nullable=True),
    # sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
