"""Added co size q

Revision ID: b6deb8b58606
Revises: 700744c45266
Create Date: 2017-10-16 17:27:53.640380

"""

# revision identifiers, used by Alembic.
revision = 'b6deb8b58606'
down_revision = '700744c45266'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('most_annoying_work_issue', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('work_life_balance', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('how_you_found_your_current_job', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('primary_programming_language_used_at_work', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('job_satisfaction', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
