"""Removing SurveyAnswers table

Revision ID: c5206ec6d840
Revises: 52f8698173d0
Create Date: 2017-10-15 18:57:37.533273

"""

# revision identifiers, used by Alembic.
revision = 'c5206ec6d840'
down_revision = '52f8698173d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_answers_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('tech_role', sa.VARCHAR(length=128), nullable=True))
    op.create_table('survey_answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('highest_educational_attainment', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
