"""Readding columns with good names

Revision ID: cdea2621fafb
Revises: 4857812d7ce4
Create Date: 2017-10-15 15:28:55.262310

"""

# revision identifiers, used by Alembic.
revision = 'cdea2621fafb'
down_revision = '4857812d7ce4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
