"""Changed feedback character limit to 1000

Revision ID: d3a7a128b9fb
Revises: b69e2751753b
Create Date: 2017-12-05 21:11:13.329799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a7a128b9fb'
down_revision = 'b69e2751753b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_column('users', 'annual_amount_earned_from_all_tech_activities_combined')
    # op.drop_column('users', 'years_of_pro_exp')
    # op.drop_column('users', 'jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('annual_amount_earned_from_all_tech_activities_combined', sa.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
