"""Bug fixing

Revision ID: f100b2ec8c3f
Revises: 47f47706a830
Create Date: 2017-11-02 09:54:42.455643

"""

# revision identifiers, used by Alembic.
revision = 'f100b2ec8c3f'
down_revision = '47f47706a830'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jobs', sa.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('years_of_pro_exp', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
